In [192]:
import pandas as pd
from copy import deepcopy
from collections import Counter
import random

import numpy as np
import statsmodels.api as sm

In [193]:
df = pd.read_csv('Bengaluru_House_Data.csv')

In [194]:
df.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [195]:
df.shape

(13320, 9)

In [196]:
df_2 = deepcopy(df)

In [197]:
df_2.dropna(inplace = True)

In [198]:
df_2.shape

(7496, 9)

In [199]:
df.dropna(subset=['size'], inplace = True)

In [200]:
df.shape

(13304, 9)

In [201]:
df['size_num'] = [float(i.split()[0]) for i in list(df['size'].values)]

In [202]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price', 'size_num'],
      dtype='object')

In [203]:
df['availability'].unique()

array(['19-Dec', 'Ready To Move', '18-May', '18-Feb', '18-Nov', '20-Dec',
       '17-Oct', '21-Dec', '19-Sep', '20-Sep', '18-Mar', '20-Feb',
       '18-Apr', '20-Aug', '18-Oct', '19-Mar', '17-Sep', '18-Dec',
       '17-Aug', '19-Apr', '18-Jun', '22-Dec', '22-Jan', '18-Aug',
       '19-Jan', '17-Jul', '18-Jul', '21-Jun', '20-May', '19-Aug',
       '18-Sep', '17-May', '17-Jun', '21-May', '18-Jan', '20-Mar',
       '17-Dec', '16-Mar', '19-Jun', '22-Jun', '19-Jul', '21-Feb',
       '19-May', '17-Nov', '20-Oct', '20-Jun', '19-Feb', '21-Oct',
       '21-Jan', '17-Mar', '17-Apr', '22-May', '19-Oct', '21-Jul',
       '21-Nov', '21-Mar', '16-Dec', '22-Mar', '20-Jan', '21-Sep',
       '21-Aug', '14-Nov', '19-Nov', '15-Nov', '16-Jul', '15-Jun',
       '17-Feb', '20-Nov', '20-Jul', '16-Sep', '15-Oct', '15-Dec',
       '16-Oct', '22-Nov', '15-Aug', '17-Jan', '16-Nov', '20-Apr',
       '16-Jan', '14-Jul'], dtype=object)

In [204]:
# [unicode(x.strip()) if x is not None else '' for x in row]
df['availability_num'] = [1 if x == 'Ready To Move' else 0 for x in list(df['availability'].values)]

In [205]:
df.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  size_num  availability_num  
0  Coomee        1056   2.0      1.0   39.07       2.0                 0  
1  Theanmp       2600   5.0      3.0  120.00       4.0                 1  
2      NaN       1440   2.0      3.0   62.00       3.0                 1  
3  Soiewre       1521   3.0      1.0   95.00       3.0                 1  
4      NaN       1200   2.0      1.0   51.00       2.0                 1

In [206]:
list(df['society'].unique())[:10]

['Coomee ',
 'Theanmp',
 nan,
 'Soiewre',
 'DuenaTa',
 'Jaades ',
 'Brway G',
 'Prrry M',
 'Shncyes',
 'Skityer']

In [207]:
df['society'].nunique()

2676

In [208]:
df[df['society'].isnull()].shape

(5499, 11)

In [209]:
df['society_num'] = [1 if str(x) != 'nan' else 0 for x in list(df['society'].values)]

In [210]:
df['society_num'].unique()

array([1, 0], dtype=int64)

In [211]:
Counter(df['society_num'].values)

Counter({1: 7805, 0: 5499})

In [212]:
df.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  size_num  availability_num  \
0  Coomee        1056   2.0      1.0   39.07       2.0                 0   
1  Theanmp       2600   5.0      3.0  120.00       4.0                 1   
2      NaN       1440   2.0      3.0   62.00       3.0                 1   
3  Soiewre       1521   3.0      1.0   95.00       3.0                 1   
4      NaN       1200   2.0      1.0   51.00       2.0                 1   

   society_num  
0            1  
1            1  
2            0  
3            1  
4            0

In [213]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price', 'size_num',
       'availability_num', 'society_num'],
      dtype='object')

In [214]:
req_cols = ['total_sqft', 'bath', 'balcony', 'price', 'size_num', 'availability_num', 'society_num']

In [215]:
df = df.loc[df['total_sqft'].str.isnumeric()]
print(df.shape)

(12978, 12)


In [216]:
df['total_sqft'] = [x.split(" ")[0] for x in list(df['total_sqft'].values)]
df['total_sqft'] = [x.split(".")[0] for x in list(df['total_sqft'].values)]
df['total_sqft'] = [x.split("P")[0] for x in list(df['total_sqft'].values)]
df['total_sqft'] = [x.split("S")[0] for x in list(df['total_sqft'].values)]
df['total_sqft'] = [x.split("A")[0] for x in list(df['total_sqft'].values)]
df['total_sqft'] = [x.split("C")[0] for x in list(df['total_sqft'].values)]
df['total_sqft'] = [x.split("G")[0] for x in list(df['total_sqft'].values)]
df['total_sqft'] = [float(x) for x in list(df['total_sqft'].values)]

In [217]:
df_2 = df[req_cols]

In [218]:
print("Before dropping nulls:", df_2.shape[0])
df_2.dropna(inplace = True)
print("After dropping nulls:", df_2.shape[0])

Before dropping nulls: 12978
After dropping nulls: 12439


E:\programfiles\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [219]:
df[df['price'].isnull()].shape

(0, 12)

In [220]:
inx = list(range(df_2.shape[0]))

In [221]:
random.shuffle(inx)

In [222]:
inx[0:5]

[1758, 9196, 10616, 10678, 7621]

In [223]:
df_2.dtypes

total_sqft          float64
bath                float64
balcony             float64
price               float64
size_num            float64
availability_num      int64
society_num           int64
dtype: object

In [224]:
df_train = df_2.iloc[inx[:round(len(inx) * 0.8)]]

In [225]:
df_test = df_2.iloc[inx[round(len(inx) * 0.8):]]

In [226]:
print(df_train.shape)
print(df_test.shape)

(9951, 7)
(2488, 7)


In [227]:
train_cols = ['total_sqft', 'bath', 'balcony', 'size_num', 'availability_num', 'society_num']

# statsmodels

In [232]:
# https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLS.html
# https://www.statsmodels.org/dev/examples/notebooks/generated/ols.html
model = sm.OLS(df_train['price'], df_train[train_cols]).fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                  price   R-squared (uncentered):                   0.601
Model:                            OLS   Adj. R-squared (uncentered):              0.601
Method:                 Least Squares   F-statistic:                              2497.
Date:                Tue, 15 Feb 2022   Prob (F-statistic):                        0.00
Time:                        23:02:13   Log-Likelihood:                         -60574.
No. Observations:                9951   AIC:                                  1.212e+05
Df Residuals:                    9945   BIC:                                  1.212e+05
Df Model:                           6                                                  
Covariance Type:            nonrobust                                                  
                       coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------

# sklearn

In [235]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(df_train[train_cols], df_train['price'])
print(reg.score(df_train[train_cols], df_train['price']))
print(reg.coef_)
print(reg.intercept_)

0.34940031902653435
[ 0.04533451 33.47626509  0.32725498 -3.31425155 -1.33303882 -9.04550627]
-35.738924349929846


In [237]:
reg.predict(df_test[train_cols])

array([106.22467443, 204.69123783,  55.44948192, ...,  67.80186604,
       141.61901378,  74.68122904])

# scipy.stats.linregress

In [243]:
from scipy.stats import linregress
from scipy.optimize import curve_fit

In [241]:
print(df_train[train_cols].shape)
print(df_train[['price']].shape)

(9951, 6)
(9951, 1)


In [245]:
def func(x, a, b, c):
    return a * np.exp(-b * x) + c

In [247]:
popt, pcov = curve_fit(func, df_train[train_cols], df_train[['price']])

ValueError: object too deep for desired array

error: Result from function call is not a proper array of floats.